version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:960b904ce82aad0772368706c971094751d40c6d2a3782baf97adccff8996c14
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
