version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:5f9074a54c0a5384cfaf7f7484636ca2dbc9dcf3c86e018dfa997d9076277fd4
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
