version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:e08eed7675600df7b937b4dc98a484da44d5b73bd7eb882eda3a1afb8cea92bb
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
