version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:6b33a7a6786a6c295fbd182023ddbce511974646eac624350968c19b7afc88da
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
