version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:af6b534e92770b106c39201d6db2f93ce4ba34dac423f0aa79727baa533aa4e8
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
