version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:c29359180871fe36dbfbfd697a7365e188c5629f58312502a7706ae58cd7b1b1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
