version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:6b311c7800f4b320b62776b7b788c332efd7f472f40f2fc0f31b15329f52529e
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
