version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:748c1e3cff6c820dd248db15268d004fc22ba8c26863fb6d8571e9fb5835d295
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
