version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:143992405bec266dfa5bd604770d26d03614eb042fffeffbe9d930466aac7cc3
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
