version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:6ff1e320d3174fdf61555837876c921e79ed9056338b3d6ecc1fa5f9961ce573
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
