version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f0f868588df5238e0a2a76184c1f165dca3947e2269cb331d845599dac64d7c7
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
