version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:71a3b195f88535d3f7bbf94d195ebdc0606c78122c6e16d714be20fed947d965
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
