version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:667b1e81c4a0b204ab70350622000bbc77642c15627ee06dc0f31edc533c57df
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
