version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:9287996b942815fb1ee1a5832d8b37174911abbaf7bd37cc2af7fb376a00f1f3
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
