version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:ddc31828cf44d3f2449cbacd2e60b0146da008b2524add446d7c4694e031aa29
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
