version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:bb3dffce8a53e0efc79b183144c64a31486f539a36e982d214e128a387f96176
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
