version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f43bfd0166bfc855211e783f0343b7f2aace41f2e8c145991c618ea07ffc530c
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
