version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:ecda228a3b853cf3db6729258be9656b8d51c899fd22114bce16da926f561d71
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
