version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:03d14fbc5caa9f4e7760c840538a50cfd5f496cc099e625030ecdb30752ccdd8
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
