version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:e4d37fed2248e89518c7d522749ff66211e65d181d61a469b47612a3bdc74a1e
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
