version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f5606808bd76606fb053258b8281ad87c48811f1c10b2222850c2a3234a36bcb
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
