version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:038040743b742c720e2d6e3ec10e67612de1ad21b709b2c292c8d8cc93bc1b26
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
