version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:366b8e06c7cfdf7d70e14f1ef204b35c4870ea4dc47b94cc08a3fc5e1c5ea8a4
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
