version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:fcf21fc38e1c962186cbae4d2811f1145b050b7416d2a0f1e6440f20476fc811
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
