version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:42a444578e730e3ac26f57223ead96db14a28fa3ad79e351964d7bedccd05f72
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
