version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:3db04db630630de7f91b30c2eaf3e5b343662266c990beb03f6818249146ef68
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
