version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:96cf7be45bad370127100a63ab5d78d6b4cd9ea56a6d749708fa85316d802684
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
