version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:5da5d585c88fb16f3c5eb449b80626ec6ae0e626a75d1b798749ea8d589ac8e9
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
