version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:501e4ed639803732e0c8f40d3e1e93cf8b0ebbf89790023770aa68dbd0603626
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
