version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f8acfc2be7341abadf4c7b5f303b0877c5e0d8ba12392d6d88ecd983f533e37b
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
