version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:f1b2dab0e55c7629b5a0bb51fe68ae1bac5b40974759f93cea196c95e8002d8f
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: npm run lint
      - run: npm run test
